### ISSUE TITLE
Anyway to use this with the node-sass cli without gulp

### ISSUE THREAD

**Issue by dogfeat** [britco/node-sass-globbing#4]
This may be a dumb question, but I'm wondering if you can use node-sass-globbing with the node-sass cli in some way, instead of through gulp. I like to just use the node-sass watch and output commands compiling while I write my sass. I am wondering node-sass-globbing can be used from the node-sass cli, and if so, how its done. Thank you.

**Comment by pdufour** [comment]
Hi there is no need to use it with gulp. Try looking at https://github.com/sass/node-sass#importer--v200---experimental
